[features]
seeds = false
skip-lint = false
[programs.localnet]
rssss = "7HFvaNrZNfws4u5qGZ9f7gfodsfzg29jvwCAv8PKMLEq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/davirain/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
